Refactor/components
Hector14oo/movies-app pull request #1
Opened 2023-06-16 02:42 UTC by Hector14oo

2023-06-16 02:50 UTC, dongeodev requested changes

2023-06-16 02:50 UTC, dongeodev commented on src/containers/Container_Home.tsx
> +        <Card_Poster
Cambiar el nombre de componente a Upper Camel Case

2023-06-16 02:50 UTC, dongeodev commented on src/app/account/forgot-password/page.tsx
> +  return <Container_ForgotPassword />;
Lo mismo usar Camel Case

2023-06-16 02:50 UTC, dongeodev commented on src/components/Input/Searcher/index.tsx
> +}: {
Crea interfaces y usalas

2023-06-16 19:24 UTC, Hector14oo commented on src/containers/Container_Home.tsx
> +        <Card_Poster
Listo.

2023-06-19 19:30 UTC, dongeodev approved these changes

2023-06-19 20:32 UTC, merged