Feature/api
Hector14oo/movies-app pull request #2
Opened 2023-06-21 01:47 UTC by Hector14oo

# PULL REQUEST 📋

## 🔹 Descripción

> Cambios:

-Cree la carpeta utils, en la cual se encuentran los archivos: Constants (Que contienen las constantes y endpoints necesarios para conectar con la API) y fetchAPI (El cual contiene la funcion para conectar a la API con los distintos endpoints)

-Cree la carpeta interfaces, la cual contiene dos custom hooks, uno para la vista Search y otro para Trending (El cual se esta usando tambien en la Home, ya que se muestran dos de las peliculas de la lista)

-Hice los cambios correspondientes a los componentes para que estuviesen tipados y estilados de la manera correcta.

-Ahora la vista de Search Movies, esta completamente funcional, el hook correspondiente tiene debounce, un estado de error, y no hace la misma consulta si el value es igual a la busqueda anterior.

-En la vita Home, las dos cards del inicio, que pertenecen a Trending, estan conectadas de igual forma.

y ya no me acuerdo que mas cambios hice 😀

## 🔹 Información para el Reviewer

> Tengame paciencia 😁

### Datos de usuario para probar el cambio:

| UserID | Username | Password | SiteID |
| ------ | -------- | -------- | ------ |
|        |          |          |        |
|        |          |          |        |

## 🔹 Tipo de PR

- [] Bugfix
- [X] Feature
- [ ] Refactoring
- [ ] Update de dependencias
- [ ] Otro (describir):

## 🔹 Capturas

[ Agregá capturas del cambio antes y después en el caso que aplique ]

## 🔹 Checklist ✔

- [ ] Probé este cambio como _Web_.
- [ ] Probé este cambio como _WebMobile_.
- [ ] Agregué _tests_ para este cambio.
- [ ] Agregué una breve descripción sobre estos cambios en el CHANGELOG para la próxima release.
- [ ] Corrí los _tests_ de forma local con el comando `npm t` y el resultado fue exitoso.
- [ ] Corrí el _chequeo de código estático_ con el comando `npm lint` y el resultado fue exitoso.
- [ ] Verifiqué que los tracks de melidata sean válidos.

## ⚠ Al no completar el template del PR el reviewer puede rechazar de forma automática el review pedido. ⚠

###### \*_Nota:_ Completar con una `x` los checks correspondientes.\*

---

© 2023 Mercado Libre

2023-06-21 15:16 UTC, dongeodev requested changes

2023-06-21 15:16 UTC, dongeodev commented on src/components/Input/Searcher/index.tsx
> +        <X
Utiliza un nombre legible para los iconos. CloseSvg o algo asi.

2023-06-21 15:16 UTC, dongeodev commented on src/containers/Search.tsx
> +  const className = error ? 'FLEX' : movies.length ? 'GRID' : 'FLEX';
```suggestion
  const className = error || !movies.length ? 'FLEX' : 'GRID'
```

2023-06-21 15:16 UTC, dongeodev commented on src/containers/Search.tsx
> +  const className = error ? 'FLEX' : movies.length ? 'GRID' : 'FLEX';
Trata de siempre escribir código legible

2023-06-21 15:16 UTC, dongeodev commented on src/hooks/useSearch.ts
> +      fecthApi(searchEndPoint(value)).then(({ results }) => {
Agrega el .catch para el manejo de errores si no lo controla se rompe la aplicacion en caso de que el servicio falle

2023-06-21 15:16 UTC, dongeodev commented on src/hooks/useTrending.ts
> +  const { results } = await fecthApi(trendingEndPoint);
Lo mismo agrega un try catch para este caso. que pasa si el servicio no responde

2023-06-21 23:57 UTC, Hector14oo commented on src/components/Input/Searcher/index.tsx
> +        <X
Nombres de iconos y figures cambiados

2023-06-23 17:53 UTC, dongeodev approved these changes

2023-06-23 17:55 UTC, merged